### ISSUE TITLE
problem with loading input files

### ISSUE THREAD

**Issue by monisobs** [CelsoReyes/ZMAP-7.0-issue-tracking#1]
Dear Celso, I get an error whenever I want to load my data file into zmap. I start matlab in the zmap-master directory, go to DATA and I choose "Create or modify *.mat file". Then the Import window popps up and I choose EQ Datafile and as format ascii columns and then press the "load" button (my file is prepared exactly as shown in the example). Please find below the error message:
Error using load
Attempt to add "NQ3c" to a static workspace.
 See Variables in Nested and Anonymous Functions.

Error in loadasci (line 66)
                load  ([newpath file1])

Error in loadasci/load_callback (line 304)
        loadasci(da,'on');
 
Error while evaluating UIControl Callback.
I'm working in a LINUX system (Ubuntu)
Have you got any idea?
Thanks for some hint and best regards
Monika

**Comment by CelsoReyes** [comment]
Hi Monika,
Try updating the latest version, which I released a little earlier today, and then give it another shot.  

I don't know if this would have solved the issue you've seen.  I had never tested ZMAP on a Linux system until today.  I had heard from a student here that Linux gave errors when loading files that we know work on the mac.
If it still doesn't work, please send me your ascii file and I'll be glad take a look... I would be unsurprised if  "Create or modify a *.mat file" is broken, since I haven't used it myself.

Regards,
Celso

**Comment by CelsoReyes** [comment]
by the way, ZMAP 7 is now available through Github, and I'll be tracking future issues there.
https://github.com/CelsoReyes/zmap7
Regards,
Celso
